apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echoflow-tls
  namespace: echoflow
spec:
  secretName: echoflow-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - echoflow.datemedoc.com
