apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoflow
  namespace: echoflow
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "30m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - echoflow.datemedoc.com
      secretName: echoflow-tls
  rules:
    - host: echoflow.datemedoc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echoflow
                port:
                  number: 80
